server:
  port: 8000

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false #是否注册Eureka服务器
    fetchRegistry: false #是否从Eureka获取注册信息
    serviceUrl:
      defaultone: http://${eureka.instance.hostname}:${server.port}/eureka/
